routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::resource('specialities', 'SpecialityController');

Route::resource('tokens', 'TokenController');

Route::resource('doctors', 'DoctorController');

Route::resource('patients', 'PatientController');

Route::get('/','Auth\LoginController@showLoginForm');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/partials/_head.blade.php
<head>
    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield('title')</title>
    
    <!-- Core CSS - Include with every page -->
    <link href="/css/bootstrap.css" rel="stylesheet" />
	<link href="/css/font-awesome.css" rel="stylesheet" />
   	{{-- <link href="/css/style.css" rel="stylesheet" /> --}}
   	{{-- <link href="/css/main-style.css" rel="stylesheet" /> --}}

<style>
		#company_name {padding-top: 25px;text-align: center;padding-bottom: 25px;font-size: 22px;}
		.mr {margin-right: 20px;}
		.fa-fw {text-align: center;}
		ul {list-style-type: none;margin:0;padding: 0;font-size: 16px;color: #fff; }
		li {border-top: 1px solid white;}
		img {margin: auto;display: table-caption;border-radius: 50%;background: #fff;width: 60px;height: 60px;padding: 5px;}
	
			 /* The side navigation menu */
		.sidenav {
		    height: 100%; /* 100% Full-height */
		    width: 0; /* 0 width - change this with JavaScript */
		    position: fixed; /* Stay in place */
		    z-index: 1; /* Stay on top */
		    top: 0;
		    left: 0;
		    background-color: #235eaa; /* Black*/
		    overflow-x: hidden; /* Disable horizontal scroll */
		    /*padding-top: 60px; /* Place content 60px from the top */*/
		    transition: 1.0s; /* 0.5 second transition effect to slide in the sidenav */
		}

		/* The navigation menu links */
		.sidenav a {
		    padding: 20px 15px;
		    /*text-decoration: none;
		    font-size: 25px;*/
		    color: #fff;
		    display: block;
		    transition: 0.3s
		}

		/* When you mouse over the navigation links, change their color */
		.sidenav a:hover, .offcanvas, a:focus{
		    background-color: #1a467f;
		}

		.active {background-color: #1a467f;}

		/* Position and style the close button (top right corner) */
		.sidenav .closebtn {
		    font-size: 36px;
		}

		/* Style page content - use this if you want to push the page content to the right when you open the side navigation */
		#main {
		    transition: margin-left .5s;
		    padding: 20px;
		}

		/* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */
		@media screen and (max-height: 450px) {
		    .sidenav {padding-top: 15px;}
		    .sidenav a {font-size: 18px;}
		} 
	</style>
</head>

resources/views/partials/_javascript.blade.php
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<script>
	
	/* Set the width of the side navigation to 250px and the left margin of the page content to 250px and add a black background color to body */
	function openNav() {
	    document.getElementById("mySidenav").style.width = "250px";
	    document.getElementById("main").style.marginLeft = "250px";
	    document.body.style.backgroundColor = "rgba(0,0,0,0.4)";
	}

	/* Set the width of the side navigation to 0 and the left margin of the page content to 0, and the background color of body to white */
	function closeNav() {
	    document.getElementById("mySidenav").style.width = "0";
	    document.getElementById("main").style.marginLeft = "0";
	    document.body.style.backgroundColor = "white";
	} 
</script>

resources/views/partials/_messages.blade.php
@if(Session::has('success'))

<div class="alert alert-success" role="alert" align="center">
	<strong>Success:</strong> {{Session::get('success')}}
</div>
@endif

@if(count($errors) > 0)

<div class="alert alert-danger">
	<strong>Errors:</strong> 
	<ul>
		@foreach($errors->all() as $error)
		<li>{{ $error }}</li>
		@endforeach
	</ul>
</div>

@endif

resources/views/partials/_nav.blade.php
 <div id="mySidenav" class="sidenav">
    
    <div style="padding-bottom: 35px;"><a href="javascript:void(0)" class="closebtn" onclick="closeNav()" style="float: right;">&times;</a></div>
    <div>
        <ul>
            <li style="border: none;">
                <div>
                    <div>
                        <img src="/images/user.jpg" alt="logo">
                    </div>
                    <div>
                        <div id="company_name">Spandan Hospital</div>      
                    </div>
                </div>
            </li>
            <li class="{{ Request::is('/patients') ? "active" : "" }}">
                <a href=" {{route('patients.index')}} ">
                    <i class="fa fa-home fa-fw mr"></i> Home
                </a>
            </li> 
               
            <li>
                <a href=" {{route('doctors.index')}} ">
                    <i class="fa fa-user-md fa-fw mr"></i> Add Doctors
                </a>
            </li>

            <li>
                <a href=" {{route('tokens.index')}} "><i class="fa fa-edit fa-fw mr"></i>Add Tokens</a>
            </li>
            <li style="border-bottom: 1px solid white;">
                <a href=" {{route('specialities.index')}} "> Add Speciality </a>
            </li>
        </ul>
    </div>
</div>

<!-- Use any element to open the sidenav -->
<div style="margin-left: 15px;margin-top: 25px;">
    <span onclick="openNav()" style="color: red;font-size: 22px;">&#9776; open</span>
</div>
















































{{-- <nav class="navbar-default navbar-static-side" role="navigation">
    
    <!-- sidebar-collapse -->
    <div class="sidebar-collapse">
        
        <!-- side-menu -->
        <ul class="nav" id="side-menu">
            <li>
                
                <!-- user image section-->
                <div class="user-section">
                    <div class="user-section-inner">
                        <img src="assets/img/user.jpg" alt="">
                    </div>
                    <div class="user-info">
                        <div>Spandan Hospital</div>      
                    </div>
                </div>  end user image section
            </li>
                            
            <li class="selected">
                <a href="panel.html">
                    <i class="fa fa-home fa-fw mr"></i> Home
                </a>
            </li> 
           
            <li>
                <a href="add_doctors.html">
                    <i class="fa fa-user-md fa-fw mr"></i> Add Doctors
                </a>
            </li>

            <li>
                <a href="add_tokens.html"><i class="fa fa-edit fa-fw mr"></i>Add Tokens</a>
            </li>
        </ul>   <!-- end side-menu -->
    </div>  <!-- end sidebar-collapse -->
</nav>  <!-- end navbar side -->
 --}}