routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::resource('specialities', 'SpecialityController');

Route::resource('tokens', 'TokenController');

Route::resource('doctors', 'DoctorController');

Route::resource('patients', 'PatientController');

Route::get('/','Auth\LoginController@showLoginForm');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/pages/add_doctors.blade.php
@extends('main')

@section('title','Admin | Add Doctors')

@section('content')
<style>
	.button {color: #ffffff;float: right;padding: 6px 8px;}
	td {vertical-align: middle;}
</style>
<div id="main">
	<div class="row"> {{-- Buttons (Modal) --}}
	    <div class="col-lg-11 col-lg-offset-1 col-md-11 col-md-offset-1 col-sm-11 col-sm-offset-1 col-xs-12">
	        <button class="btn btn-primary" type="submit" data-toggle="modal" data-target="#add-doctor">
	        	<i class="fa fa-user-md"></i> Add Doctor
	        </button>
	        <div class="modal fade" id="add-doctor" role="dialog">
		      	<div class="modal-dialog">
		            <div class="modal-content">
		            	<div class="modal-header">
		            		<button type="button" class="close" data-dismiss="modal"></button>
		                	<h1 class="modal-title">Add Doctor</h1><br>
		                </div>
		                <div class="modal-body">

		              		<form method="POST" action=" {{route('doctors.store')}} " id="doctormodal">
		              			{{csrf_field()}}
			                	<div class="form-group">
			                    	<label for="fname" class="control-label">First Name</label>
			                    	<input type="text" name="first_name" placeholder="First name" class="form-control" id="fname">
			                	</div>

			                	<div class="form-group">
			                    	<label for="lname" class="control-label">Last Name</label>
			                    	<input type="text" name="last_name" placeholder="Last name" class="form-control" id="lname">
			                	</div>

		                        <div class="form-group">
		                          	<label for="speciality"> Speciality (Select One) </label>
		                          	<select name="speciality" class="form-control" id="speciality" form="doctormodal">
		                          		@foreach($specialities as $speciality)
		                          			<option value="{{$speciality->id}}">{{$speciality->name}}</option>
		                          		@endforeach
		                          	</select>
	                        	</div> 
			                	<div style="text-align: center;">
			                		<button class="btn btn-success btn-lg" type="submit" style="padding-left: 40px;padding-right: 40px;margin-top: 20px;">Save</button>
			                	</div>
							</form>
						</div>
		              	<div class="modal-footer">
		                    <button class="btn btn-danger" data-dismiss="modal" type="reset">Close</button>
		             	</div>
		            </div>
		        </div>
		    </div>
	    </div>
	</div>
	
	<div class="row">
		<div class="col-lg-11 col-lg-offset-1 col-md-11 col-md-offset-1 col-sm-11 col-sm-offset-1 col-xs-12">
			<div class="table-responsive" style="margin-top: 40px;">
				<table class="table" style="font-size: 16px;">
					<tr>
						<th>Sr No.</th>
						<th>First Name</th>
						<th>Last Name</th>
						<th>Speciality</th>
					</tr>
					@foreach($doctors as $doctor)
						<tr>
							<td> {{$loop->index+1}} </td>
							<td> {{$doctor->first_name}} </td>
							<td> {{$doctor->last_name}} </td>
							<td> {{$doctor->speciality->name}} </td>
							<td> <a href="" class="button" style="background-color: red;"> <i class="fa fa-trash-o"> </i> </a> </td>
						</tr>
					@endforeach
				</table>
			</div>
		</div>
	</div>
</div>


@stop

resources/views/pages/add_patients.blade.php
@extends('main')

@section('title','Admin | Add Patients')

@section('content')
<style>
	.button {color: #ffffff;padding: 6px 8px;}
	td {vertical-align: middle;text-align: center;}
	th {text-align: center;
</style>
<div id="main">
	<div class="row"> {{-- Buttons (Modal) --}}
	    <div class="col-lg-11 col-lg-offset-1 col-md-11 col-md-offset-1 col-sm-11 col-sm-offset-1 col-xs-12">
	        <button class="btn btn-primary" type="submit" data-toggle="modal" data-target="#add-patient">
	        	<i class="fa fa-user-md"></i> Add Patient
	        </button>
	        <div class="modal fade" id="add-patient" role="dialog">
		      	<div class="modal-dialog">
		            <div class="modal-content">
		            	<div class="modal-header">
		            		<button type="button" class="close" data-dismiss="modal"></button>
		                	<h1 class="modal-title">Add Patient</h1><br>
		                </div>
		                <div class="modal-body">

		              		<form method="POST" action=" {{route('patients.store')}} " id="patientmodal">
		              			{{csrf_field()}}
			                	<div class="form-group">
			                    	<label for="fname" class="control-label">First Name</label>
			                    	<input type="text" name="first_name" placeholder="First name" class="form-control" id="fname">
			                	</div>

			                	<div class="form-group">
			                    	<label for="lname" class="control-label">Last Name</label>
			                    	<input type="text" name="last_name" placeholder="Last name" class="form-control" id="lname">
			                	</div>

		                        <div class="form-group">
		                          	<label for="token"> Token No. (Select One) </label>
		                          	<select name="token" class="form-control" id="token" form="patientmodal">
		                          		@foreach($tokens as $token)
                     			<option value="{{$token->id}}">{{$token->token_number}}</option>
		                          		@endforeach
		                          	</select>
	                        	</div> 
	                        	<div class="form-group">
		                          	<label for="doctor"> Doctor (Select One) </label>
		                          	<select name="doctor" class="form-control" id="doctor" form="patientmodal">
		                          		@foreach($doctors as $doctor)
		                          			<option value="{{$doctor->id}}">{{$doctor->first_name. " " .$doctor->last_name}}</option>
		                          		@endforeach
		                          	</select>
	                        	</div> 
			                	<div style="text-align: center;">
			                		<button class="btn btn-success btn-lg" type="submit" style="padding-left: 40px;padding-right: 40px;margin-top: 20px;">Save</button>
			                	</div>
							</form>
						</div>
		              	<div class="modal-footer">
		                    <button class="btn btn-danger" data-dismiss="modal" type="reset">Close</button>
		             	</div>
		            </div>
		        </div>
		    </div>
	    </div>
	</div>
	
	<div class="row">
		<div class="col-lg-11 col-lg-offset-1 col-md-11 col-md-offset-1 col-sm-11 col-sm-offset-1 col-xs-12">
			<div class="table-responsive" style="margin-top: 40px;">
				<table class="table" style="font-size: 16px;">
					<tr>
						<th>Sr No.</th>
						<th>First Name</th>
						<th>Last Name</th>
						<th>Token No.</th>
						<th>Doctor's Name</th>
						<th></th>
						<align: center;<
						th {text-align: center;/th>
					</tr>
					@foreach($patients as $patient)
						<tr>
							<td> {{$loop->index+1}} </td>
							<td> {{$patient->first_name}} </td>
							<td> {{$patient->last_name}} </td>
							<td> {{$patient->token->token_number}} </td>
							<td> {{$patient->doctor[0]->first_name. " " .$patient->doctor[0]->last_name}} </td>
							<td> <a href="" class="button" style="background-color:green; "> <i class="fa fa-phone"> </i> </a> </td>
							<td> 
								<form action="{{route('patients.destroy',$patient->id)}}" method="POST">
									{{csrf_field()}}
									<input type="hidden" name="_method" value="DELETE">
									<button type="submit" class="fa fa-trash-o button" style="background-color: red;border: none;">
									</button>
								</form>
							</td>
						</tr>
					@endforeach
				</table>
			</div>
		</div>
	</div>
</div>


@stop

resources/views/pages/add_speciality.blade.php
@extends('main')

@section('title','Admin | Add Speciality')

@section('content')

<div id="main">
	<div class="row">
		<div class="col-lg-11 col-md-11 col-sm-11 col-xs-12 col-lg-offset-1 col-md-offset-1 col-sm-offset-1">
			<button class="btn btn-primary" type="submit" data-toggle="modal" data-target="#add-speciality">
		        <i class="fa fa-plus"></i> Add Speciality
		    </button>
	        <div class="modal fade" id="add-speciality" role="dialog">
		      	<div class="modal-dialog">
		            <div class="modal-content">
		            	<div class="modal-header">
		            		<button type="button" class="close" data-dismiss="modal"></button>
		                	<h1 class="modal-title">Add Speciality</h1><br>
		                </div>
		                <div class="modal-body">

		              		<form method="POST" action=" {{route('specialities.store')}} ">
		              			{{csrf_field()}}
			                	<div class="form-group">
			                    	<label for="speciality" class="control-label"> Speciality </label>
			                    	<input type="text" name="speciality" placeholder="Enter the Speciality you want to save" class="form-control" id="speciality">
			                	</div>
			                	<div style="text-align: center;">
			                		<button class="btn btn-success btn-lg" type="submit" style="padding-left: 40px;padding-right: 40px;margin-top: 20px;">Save</button>
			                	</div>
							</form>
						</div>
		              	<div class="modal-footer">
		                    <button class="btn btn-danger" data-dismiss="modal" type="reset">Close</button>
		             	</div>
		            </div>
		        </div>
		    </div>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-11 col-lg-offset-1 col-md-11 col-md-offset-1 col-sm-11 col-sm-offset-1 col-xs-12">
			<div class="table-responsive" style="margin-top: 40px;">
				<table class="table">
					<tr>
						<th>Sr No.</th>
						<th>Speciality</th>
					</tr>
					@foreach($specialities as $speciality)
						<tr>
							<td> {{$loop->index+1}} </td>>
							<td> {{$speciality->name}} </td>
						</tr>
					@endforeach
				</table>
			</div>
		</div>
	</div>
</div>

@stop

resources/views/pages/add_tokens.blade.php
@extends('main')

@section('title','Admin | Add Token')

@section('content')

<style>
	.button {color: #ffffff;padding: 6px 8px;}
	td {vertical-align: middle;text-align: center;}
	th {text-align: center;}
</style>
<div id="main">
	<div class="row"> {{-- Buttons (Modal) --}}
	    <div class="col-lg-11 col-lg-offset-1 col-md-11 col-md-offset-1 col-sm-11 col-sm-offset-1 col-xs-12">
	        <button class="btn btn-primary" type="submit" data-toggle="modal" data-target="#add-token">
	        	<i class="fa fa-user-md"></i> Add Token
	        </button>
	        <div class="modal fade" id="add-token" role="dialog">
		      	<div class="modal-dialog">
		            <div class="modal-content">
		            	<div class="modal-header">
		            		<button type="button" class="close" data-dismiss="modal"></button>
		                	<h1 class="modal-title">Add Token</h1><br>
		                </div>
		                <div class="modal-body">

		              		<form method="POST" action=" {{route('tokens.store')}} " id="tokenmodal">
		              			{{csrf_field()}}

			                	<div class="alert-danger"><p>Enter the range of the token numbers to be created</p></div>
			                	<div class="form-group">
			                    	<label for="token_start" class="control-label">Start No.</label>
			                    	<input type="number" name="token_start" placeholder="Start Token No." class="form-control" id="token_start">
			                	</div>

								<div class="form-group">
			                    	<label for="token_end" class="control-label">End No.</label>
			                    	<input type="number" name="token_end" placeholder="End Token No." class="form-control" id="token_end">
			                	</div>


			                	<div style="text-align: center;">
			                		<button class="btn btn-success btn-lg" type="submit" style="padding-left: 40px;padding-right: 40px;margin-top: 20px;">Save</button>
			                	</div>
							</form>
						</div>
		              	<div class="modal-footer">
		                    <button class="btn btn-danger" data-dismiss="modal" type="reset">Close</button>
		             	</div>
		            </div>
		        </div>
		    </div>
	    </div>
	</div>
	
	<div class="row">
		<div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-12">
			<div class="table-responsive" style="margin-top: 40px;">
				<table class="table table-bordered">
					<tr>
						<th>Sr No.</th>
						<th>Token No.</th>
						<th></th>
					</tr>
					@foreach($tokens as $token)
						<tr>
							<td> {{$loop->index+1}} </td>
							<td> {{$token->token_number}} </td>
							<td> 
								<form action="{{route('tokens.destroy',$token->id)}}" method="POST">
									{{csrf_field()}}
									<input type="hidden" name="_method" value="DELETE">
									<button type="submit" class="fa fa-trash-o button" style="background-color: red;border: none;">
									</button>
								</form>
							</td>
						</tr>
					@endforeach
				</table>
			</div>
		</div>
	</div>
</div>

@stop

resources/views/pages/login.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Login</title>

        <!-- Core CSS - Include with every page -->
        <link href="/css/bootstrap.css" rel="stylesheet" />
        <link href="/css/font-awesome.css" rel="stylesheet" />
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-md-offset-4">
                    <div class="panel panel-default login-panel">
                        <div class="panel-heading">
                            <h3 class="panel-title">Login</h3>
                        </div>
                        <div class="panel-body">
                            <form role="form" method="POST" action="">
                                <fieldset>
                                    <div class="form-group">
                                        <input class="form-control" placeholder="example@xyz.com" name="email" type="text">
                                    </div>
                                    <div class="form-group">
                                        <input class="form-control" placeholder="Password" name="password" type="password" value="">
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input name="remember" type="checkbox" value="Remember Me"> Remember Me
                                        </label>
                                    </div>
                                    <input class="btn btn-lg btn-success btn-block" type="submit" value="Submit">
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>